[package]
name = "mp"
version = "0.1.0"
edition = "2021"

[dependencies]
probe-rs = { git = "https://github.com/tommy-gilligan/probe-rs.git", default-features = false, features = [ "builtin-targets", "rtt" ] }
tempfile = "3.8.0"
uf2-decode = "0.1.0"
